# Generated by Django 6.0.4 on 2026-04-22 18:54

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", models.CharField(max_length=512)),
                ("expression", models.CharField(blank=True, max_length=1024)),
                ("force_refresh_requested", models.BooleanField(default=False)),
                ("freshness_days_used", models.IntegerField(default=14)),
                ("status", models.CharField(default="queued", max_length=32)),
                ("stage", models.CharField(default="queued", max_length=64)),
                ("message", models.TextField(blank=True)),
                ("source_total", models.IntegerField(default=0)),
                ("source_done", models.IntegerField(default=0)),
                ("source_live", models.IntegerField(default=0)),
                ("source_failed", models.JSONField(default=list)),
                ("index_hits_before", models.IntegerField(default=0)),
                ("index_hits_after", models.IntegerField(default=0)),
                ("rescan_triggered", models.BooleanField(default=False)),
                ("rescan_reason", models.CharField(blank=True, max_length=64)),
                ("results", models.JSONField(default=list)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="search_sear_status_ae1663_idx",
                    ),
                    models.Index(
                        fields=["query", "created_at"],
                        name="search_sear_query_c9ca3c_idx",
                    ),
                ],
            },
        ),
    ]
