# Generated by Django 6.0.4 on 2026-04-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchjob",
            name="source_timings",
            field=models.JSONField(default=dict),
        ),
    ]
