# Generated by Django 6.0.4 on 2026-04-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0002_searchjob_source_timings"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchjob",
            name="substage",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="searchjob",
            name="substage_label",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
