# Generated by Django 6.0.4 on 2026-04-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0003_searchjob_substage_searchjob_substage_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchWaitStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("without_enrichment", "Without enrichment"),
                            ("with_enrichment", "With enrichment"),
                        ],
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("average_seconds", models.FloatField(default=0.0)),
                ("sample_count", models.PositiveIntegerField(default=0)),
                ("seeded_from_history_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["kind"], name="search_sear_kind_2713ca_idx"),
                ],
            },
        ),
    ]
