# Generated by Django 6.0.4 on 2026-05-26 21:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0004_searchwaitstat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="searchwaitstat",
            name="seeded_from_history_at",
        ),
    ]
