# Generated by Django 6.0.6 on 2026-08-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0006_searchjob_filter_sort_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchjob",
            name="exclude_retracted",
            field=models.BooleanField(default=False),
        ),
    ]
