// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for SearchFiltersSortBy.
const (
	SearchFiltersSortByMetadata  SearchFiltersSortBy = "metadata"
	SearchFiltersSortByNewest    SearchFiltersSortBy = "newest"
	SearchFiltersSortByRelevance SearchFiltersSortBy = "relevance"
)

// Valid indicates whether the value is a known member of the SearchFiltersSortBy enum.
func (e SearchFiltersSortBy) Valid() bool {
	switch e {
	case SearchFiltersSortByMetadata:
		return true
	case SearchFiltersSortByNewest:
		return true
	case SearchFiltersSortByRelevance:
		return true
	default:
		return false
	}
}

// Defines values for SearchJobCreateRequestSortBy.
const (
	SearchJobCreateRequestSortByMetadata  SearchJobCreateRequestSortBy = "metadata"
	SearchJobCreateRequestSortByNewest    SearchJobCreateRequestSortBy = "newest"
	SearchJobCreateRequestSortByRelevance SearchJobCreateRequestSortBy = "relevance"
)

// Valid indicates whether the value is a known member of the SearchJobCreateRequestSortBy enum.
func (e SearchJobCreateRequestSortBy) Valid() bool {
	switch e {
	case SearchJobCreateRequestSortByMetadata:
		return true
	case SearchJobCreateRequestSortByNewest:
		return true
	case SearchJobCreateRequestSortByRelevance:
		return true
	default:
		return false
	}
}

// Defines values for SearchRequestSortBy.
const (
	SearchRequestSortByMetadata  SearchRequestSortBy = "metadata"
	SearchRequestSortByNewest    SearchRequestSortBy = "newest"
	SearchRequestSortByRelevance SearchRequestSortBy = "relevance"
)

// Valid indicates whether the value is a known member of the SearchRequestSortBy enum.
func (e SearchRequestSortBy) Valid() bool {
	switch e {
	case SearchRequestSortByMetadata:
		return true
	case SearchRequestSortByNewest:
		return true
	case SearchRequestSortByRelevance:
		return true
	default:
		return false
	}
}

// EligibilityConfidence defines model for EligibilityConfidence.
type EligibilityConfidence struct {
	DoiAndJournalCard *float64 `json:"doi_and_journal_card,omitempty"`
	Indexed           *float64 `json:"indexed,omitempty"`
	NotPreprint       *float64 `json:"not_preprint,omitempty"`
	Overall           *float64 `json:"overall,omitempty"`
	PeerReviewed      *float64 `json:"peer_reviewed,omitempty"`
}

// EligibilityEvidence defines model for EligibilityEvidence.
type EligibilityEvidence struct {
	DoiAndJournalCard *bool `json:"doi_and_journal_card,omitempty"`
	Indexed           *bool `json:"indexed,omitempty"`
	NotPreprint       *bool `json:"not_preprint,omitempty"`
	PeerReviewed      *bool `json:"peer_reviewed,omitempty"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Errors *[]ErrorItem `json:"errors,omitempty"`
	Type   *string      `json:"type,omitempty"`
}

// ErrorItem defines model for ErrorItem.
type ErrorItem struct {
	Attr   *string `json:"attr,omitempty"`
	Code   *string `json:"code,omitempty"`
	Detail *string `json:"detail,omitempty"`
}

// Quote defines model for Quote.
type Quote struct {
	Location  *string  `json:"location,omitempty"`
	Rationale *string  `json:"rationale,omitempty"`
	Relevance *float64 `json:"relevance,omitempty"`
	Text      *string  `json:"text,omitempty"`
}

// ReindexRequest defines model for ReindexRequest.
type ReindexRequest struct {
	Query *string `json:"query,omitempty"`
}

// ReindexResponse defines model for ReindexResponse.
type ReindexResponse struct {
	Status *string `json:"status,omitempty"`
	TaskId *string `json:"task_id,omitempty"`
}

// SearchFilters defines model for SearchFilters.
type SearchFilters struct {
	ExcludePreprints *bool                `json:"exclude_preprints,omitempty"`
	ExcludeRetracted *bool                `json:"exclude_retracted,omitempty"`
	IndexedOnly      *bool                `json:"indexed_only,omitempty"`
	PeerReviewedOnly *bool                `json:"peer_reviewed_only,omitempty"`
	SortBy           *SearchFiltersSortBy `json:"sort_by,omitempty"`
	YearFrom         *int                 `json:"year_from,omitempty"`
	YearTo           *int                 `json:"year_to,omitempty"`
}

// SearchFiltersSortBy defines model for SearchFilters.SortBy.
type SearchFiltersSortBy string

// SearchJobCreateRequest defines model for SearchJobCreateRequest.
type SearchJobCreateRequest struct {
	ExcludePreprints *bool                         `json:"exclude_preprints,omitempty"`
	ExcludeRetracted *bool                         `json:"exclude_retracted,omitempty"`
	Expression       *string                       `json:"expression,omitempty"`
	ForceRefresh     *bool                         `json:"force_refresh,omitempty"`
	IndexedOnly      *bool                         `json:"indexed_only,omitempty"`
	PeerReviewedOnly *bool                         `json:"peer_reviewed_only,omitempty"`
	Query            string                        `json:"query"`
	SortBy           *SearchJobCreateRequestSortBy `json:"sort_by,omitempty"`
	YearFrom         *int                          `json:"year_from,omitempty"`
	YearTo           *int                          `json:"year_to,omitempty"`
}

// SearchJobCreateRequestSortBy defines model for SearchJobCreateRequest.SortBy.
type SearchJobCreateRequestSortBy string

// SearchJobPayload defines model for SearchJobPayload.
type SearchJobPayload struct {
	AttachedToExisting                  *bool                    `json:"attached_to_existing,omitempty"`
	AverageWaitWithEnrichmentSeconds    *int                     `json:"average_wait_with_enrichment_seconds,omitempty"`
	AverageWaitWithoutEnrichmentSeconds *int                     `json:"average_wait_without_enrichment_seconds,omitempty"`
	Count                               *int                     `json:"count,omitempty"`
	CreatedAt                           *time.Time               `json:"created_at,omitempty"`
	Error                               *string                  `json:"error,omitempty"`
	ExcludePreprints                    *bool                    `json:"exclude_preprints,omitempty"`
	ExcludeRetracted                    *bool                    `json:"exclude_retracted,omitempty"`
	Expression                          *string                  `json:"expression,omitempty"`
	FinishedAt                          *time.Time               `json:"finished_at,omitempty"`
	FreshnessDaysUsed                   *int                     `json:"freshness_days_used,omitempty"`
	Id                                  *openapi_types.UUID      `json:"id,omitempty"`
	IndexHitsAfter                      *int                     `json:"index_hits_after,omitempty"`
	IndexHitsBefore                     *int                     `json:"index_hits_before,omitempty"`
	IndexedOnly                         *bool                    `json:"indexed_only,omitempty"`
	Message                             *string                  `json:"message,omitempty"`
	Page                                *int                     `json:"page,omitempty"`
	PeerReviewedOnly                    *bool                    `json:"peer_reviewed_only,omitempty"`
	PerPage                             *int                     `json:"per_page,omitempty"`
	ProgressPercent                     *int                     `json:"progress_percent,omitempty"`
	Query                               *string                  `json:"query,omitempty"`
	RescanReason                        *string                  `json:"rescan_reason,omitempty"`
	RescanTriggered                     *bool                    `json:"rescan_triggered,omitempty"`
	Results                             *[]SearchResult          `json:"results,omitempty"`
	SortBy                              *string                  `json:"sort_by,omitempty"`
	SourceDone                          *int                     `json:"source_done,omitempty"`
	SourceFailed                        *[]string                `json:"source_failed,omitempty"`
	SourceLive                          *int                     `json:"source_live,omitempty"`
	SourceStats                         *SourceStats             `json:"source_stats,omitempty"`
	SourceTimings                       *map[string]SourceTiming `json:"source_timings,omitempty"`
	SourceTotal                         *int                     `json:"source_total,omitempty"`
	Stage                               *string                  `json:"stage,omitempty"`
	Status                              *string                  `json:"status,omitempty"`
	Substage                            *string                  `json:"substage,omitempty"`
	SubstageLabel                       *string                  `json:"substage_label,omitempty"`
	TotalPages                          *int                     `json:"total_pages,omitempty"`
	TotalResults                        *int                     `json:"total_results,omitempty"`
	UpdatedAt                           *time.Time               `json:"updated_at,omitempty"`
	YearFrom                            *int                     `json:"year_from,omitempty"`
	YearTo                              *int                     `json:"year_to,omitempty"`
}

// SearchRequest defines model for SearchRequest.
type SearchRequest struct {
	ExcludePreprints *bool                `json:"exclude_preprints,omitempty"`
	ExcludeRetracted *bool                `json:"exclude_retracted,omitempty"`
	Expression       *string              `json:"expression,omitempty"`
	ForceRefresh     *bool                `json:"force_refresh,omitempty"`
	IndexedOnly      *bool                `json:"indexed_only,omitempty"`
	Page             *int                 `json:"page,omitempty"`
	PeerReviewedOnly *bool                `json:"peer_reviewed_only,omitempty"`
	PerPage          *int                 `json:"per_page,omitempty"`
	Query            string               `json:"query"`
	SortBy           *SearchRequestSortBy `json:"sort_by,omitempty"`
	YearFrom         *int                 `json:"year_from,omitempty"`
	YearTo           *int                 `json:"year_to,omitempty"`
}

// SearchRequestSortBy defines model for SearchRequest.SortBy.
type SearchRequestSortBy string

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Count       *int            `json:"count,omitempty"`
	Page        *int            `json:"page,omitempty"`
	PerPage     *int            `json:"per_page,omitempty"`
	Query       *string         `json:"query,omitempty"`
	Results     *[]SearchResult `json:"results,omitempty"`
	SourceStats *SourceStats    `json:"source_stats,omitempty"`
	TotalPages  *int            `json:"total_pages,omitempty"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	Authors               *[]string              `json:"authors,omitempty"`
	CitedByCount          *int                   `json:"cited_by_count,omitempty"`
	Doi                   *string                `json:"doi,omitempty"`
	EligibilityConfidence *EligibilityConfidence `json:"eligibility_confidence,omitempty"`
	EligibilityEvidence   *EligibilityEvidence   `json:"eligibility_evidence,omitempty"`
	Id                    *int64                 `json:"id,omitempty"`
	Identifiers           *map[string]string     `json:"identifiers,omitempty"`
	IsRetracted           *bool                  `json:"is_retracted,omitempty"`
	Issue                 *string                `json:"issue,omitempty"`
	Journal               *string                `json:"journal,omitempty"`
	Pages                 *string                `json:"pages,omitempty"`
	Preview               *string                `json:"preview,omitempty"`
	PublicationDate       *openapi_types.Date    `json:"publication_date,omitempty"`
	Quotes                *[]Quote               `json:"quotes,omitempty"`
	RerankScore           *float64               `json:"rerank_score,omitempty"`
	RetractionNote        *string                `json:"retraction_note,omitempty"`
	Source                *string                `json:"source,omitempty"`
	Tier                  *string                `json:"tier,omitempty"`
	Title                 *string                `json:"title,omitempty"`
	Tldr                  *string                `json:"tldr,omitempty"`
	Url                   *string                `json:"url,omitempty"`
	Volume                *string                `json:"volume,omitempty"`
	Year                  *int                   `json:"year,omitempty"`
}

// SourceStats defines model for SourceStats.
type SourceStats struct {
	Failed *[]string `json:"failed,omitempty"`
	Live   *int      `json:"live,omitempty"`
	Total  *int      `json:"total,omitempty"`
}

// SourceTiming defines model for SourceTiming.
type SourceTiming struct {
	ArticlesCount *int     `json:"articles_count,omitempty"`
	EnrichSeconds *float64 `json:"enrich_seconds,omitempty"`
	FetchSeconds  *float64 `json:"fetch_seconds,omitempty"`
	SaveSeconds   *float64 `json:"save_seconds,omitempty"`
	Status        *string  `json:"status,omitempty"`
	TotalSeconds  *float64 `json:"total_seconds,omitempty"`
}

// GetSearchJobParams defines parameters for GetSearchJob.
type GetSearchJobParams struct {
	Page    *int `form:"page,omitempty" json:"page,omitempty"`
	PerPage *int `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// ReindexArticlesJSONRequestBody defines body for ReindexArticles for application/json ContentType.
type ReindexArticlesJSONRequestBody = ReindexRequest

// SearchArticlesJSONRequestBody defines body for SearchArticles for application/json ContentType.
type SearchArticlesJSONRequestBody = SearchRequest

// CreateSearchJobJSONRequestBody defines body for CreateSearchJob for application/json ContentType.
type CreateSearchJobJSONRequestBody = SearchJobCreateRequest
