# Generated by Django 6.0.4 on 2026-04-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=512)),
                ('source_key', models.CharField(max_length=64)),
                ('status', models.CharField(default='started', max_length=32)),
                ('error', models.TextField(blank=True)),
                ('fetched', models.IntegerField(default=0)),
                ('eligible', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
