# Generated by Django 6.0.4 on 2026-05-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0002_localimportfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExaApiKeyQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key_id", models.CharField(max_length=64, unique=True)),
                ("api_key_name", models.CharField(blank=True, max_length=128)),
                (
                    "rate_limit_per_minute",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "usage_total_cost_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("usage_breakdown", models.JSONField(blank=True, default=list)),
                ("usage_window_start", models.DateTimeField(blank=True, null=True)),
                ("usage_window_end", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
            ],
        ),
    ]
