# Generated by Django 6.0.4 on 2026-07-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_citation_style',
        ),
    ]
