# Generated by Django 6.0.4 on 2026-04-21 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('issn', models.CharField(blank=True, max_length=32)),
                ('eissn', models.CharField(blank=True, max_length=32)),
                ('publisher', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('base_url', models.URLField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=1000)),
                ('abstract', models.TextField(blank=True)),
                ('full_text', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=32)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(max_length=1000)),
                ('doi', models.CharField(blank=True, max_length=256)),
                ('volume', models.CharField(blank=True, max_length=32)),
                ('issue', models.CharField(blank=True, max_length=32)),
                ('pages', models.CharField(blank=True, max_length=32)),
                ('is_open_access', models.BooleanField(default=True)),
                ('is_peer_reviewed_or_refereed', models.BooleanField(default=False)),
                ('is_indexed_in_reputable_db', models.BooleanField(default=False)),
                ('has_doi_and_journal_card', models.BooleanField(default=False)),
                ('is_not_preprint_or_author_manuscript', models.BooleanField(default=False)),
                ('is_eligible', models.BooleanField(default=False)),
                ('peer_review_evidence', models.TextField(blank=True)),
                ('indexing_evidence', models.TextField(blank=True)),
                ('doi_journal_evidence', models.TextField(blank=True)),
                ('preprint_evidence', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.journal')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.source')),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=512)),
                ('content', models.TextField()),
                ('offset_start', models.IntegerField(default=0)),
                ('offset_end', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_authors', to='articles.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.author')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('article', 'author', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=255)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='articles.article')),
            ],
            options={
                'unique_together': {('article', 'kind', 'value')},
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_eligible', 'publication_year'], name='articles_ar_is_elig_d76794_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['doi'], name='articles_ar_doi_f0d052_idx'),
        ),
    ]
