# Generated by Django 6.0.4 on 2026-04-25 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_confidence_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('passage_index', models.PositiveIntegerField()),
                ('section', models.CharField(blank=True, max_length=128)),
                ('content', models.TextField()),
                ('offset_start', models.IntegerField(default=0)),
                ('offset_end', models.IntegerField(default=0)),
                (
                    'article',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='passages',
                        to='articles.article',
                    ),
                ),
            ],
            options={
                'ordering': ['article_id', 'passage_index'],
                'indexes': [
                    models.Index(
                        fields=['article', 'passage_index'],
                        name='articles_pa_article_1eae5f_idx',
                    ),
                    models.Index(
                        fields=['article', 'section'],
                        name='articles_pa_article_b656cc_idx',
                    ),
                ],
                'unique_together': {('article', 'passage_index')},
            },
        ),
    ]
