# Generated by Django 6.0.4 on 2026-05-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0005_remove_passage_and_snippet"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="search_vector",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.URLField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="author",
            name="full_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="journal",
            name="name",
            field=models.CharField(db_index=True, max_length=300),
        ),
    ]
