# Generated by Django 6.0.4 on 2026-05-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0007_delete_articles_without_doi"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articleauthor",
            options={"ordering": ("order",)},
        ),
        migrations.AlterField(
            model_name="article",
            name="doi",
            field=models.CharField(max_length=256),
        ),
    ]
