# Generated by Django 6.0.4 on 2026-07-04 12:16

from django.db import migrations, models


def deduplicate_articles_by_doi(apps, schema_editor):
    # Collapse duplicate Article rows that share a DOI before the unique
    # constraint is applied. The ingestion service used to upsert on
    # (source, url), so the same article fetched from two sources (or two
    # URLs) could produce two rows with the same DOI. ArticleAuthor and
    # Identifier cascade on Article deletion; LocalImportFile.article uses
    # SET_NULL, so those records stay with article=NULL.
    Article = apps.get_model("articles", "Article")
    duplicates = (
        Article.objects.values("doi")
        .annotate(count=models.Count("id"))
        .filter(count__gt=1)
    )
    for group in duplicates:
        articles = Article.objects.filter(doi=group["doi"])
        # Prefer an eligible article, then the most recently updated, then
        # the highest pk as a stable tie-breaker.
        canonical = articles.order_by(
            "-is_eligible",
            "-updated_at",
            "-id",
        ).first()
        articles.exclude(pk=canonical.pk).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0008_alter_articleauthor_options_alter_article_doi"),
    ]

    operations = [
        migrations.RunPython(
            deduplicate_articles_by_doi,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="article",
            name="doi",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
