# Generated by Django 6.0.6 on 2026-08-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_local_md_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cited_by_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='is_retracted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='retraction_note',
            field=models.TextField(blank=True),
        ),
    ]
